<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
$tableParams = [
    'tableId' => 'mage2-events-tree',
    'tableWidth' => '4',
];
?>

<div>
    <?php echo $this->zrayTable($tableParams); //zrayTableHtml ?>
</div>

<script type="text/javascript">
    (function () {
        var storage = zray.getStorage('mevents');
        // create main table
        var maintable = zray.createGeneralTreeTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
        maintable.setColumns([
            {
                label: 'index',
                propertyName: 'observers',
                sortable: true,
                width: 80
            },
            {
                label: 'area',
                propertyName: 'area',
                sortable: true,
                width: 90
            },
            {
                label: 'Event / Observer',
                propertyName: 'name',
                sortable: true
            },
            {
                label: 'Duration (ms)',
                propertyName: 'duration',
                sortable: true,
                width: 100,
                getHtml: function (val, rec) {
                    if (val) {
                        return val;
                    }
                    return val.toFixed(3);
                }
            },
            {
                label: 'Class::Method',
                propertyName: 'class',
                sortable: true,
                getHtml: function (val, rec) {
                    if (rec.method) {
                        val = val + '::' + rec.method;
                    }
                    if (!val || !rec.classFile || rec.classFile.length < 5 || !zray.getFileActions || !zray.showInIde) {
                        return val;
                    }

                    var showInIDEParams = {
                        filePath: rec.classFile,
                        line: rec.methodLine || 1,
                        fullUrl: document.location.href
                    };
                    return zray.getFileActions(val, val, rec.classFile, showInIDEParams);
                }
            },
            {
                label: 'Args',
                propertyName: 'args',
                sortable: true
            }
        ]);
        // create main table - end

        // create pager
        zray.createPager(storage, jQuery('#magento-events-pager'));
        // create search
        zray.createSearch(storage, jQuery('#magento-events-search'), maintable);
        if (maintable.getChildrenRepresentation && maintable.getChildrenRepresentation.length > 2 && maintable.setRootHtml) {
            //debugger;
            maintable.setRootHtml(function (children, parent) {
                if (parent && parent.id) {
                    return parent.id;
                }
                return 'Not Available';
            });
        }
        zray.registerDataHandler('Magento2', 'mevents', function (extensionData, requestData) {
            jQuery.each(extensionData, function (k, v) {
                var durationSum = 0;
                jQuery.each(v.observers, function (k2, v2) {
                    durationSum += parseFloat(v2.duration);
                });
                extensionData[k].duration = durationSum.toFixed(3);
            });
            storage.setData(extensionData);
            zray.updateMenuTitle('Magento2', 'events', 'Events (' + extensionData.length + ')');
        });

    })();
</script>
