<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
$tableParams = [
    'tableId' => 'mage2-intercepted-tree',
    'tableWidth' => '4',
];
?>

<div>
    <?php echo $this->zrayTable($tableParams); //zrayTableHtml ?>
</div>

<script type="text/javascript">
    (function () {
        var storage = zray.getStorage('intercepted');
        // create main table
        var maintable = zray.createGeneralTreeTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
        maintable.setColumns([
            {
                label: '',
                propertyName: 'plugins',
                sortable: false,
                width: 22
            },
            {
                label: 'Class::Method',
                propertyName: 'class',
                sortable: true,
                getHtml: function (val, rec) {
                    if (rec.method) {
                        val = val + '::' + rec.method;
                    }
                    if (!val || !rec.classFile || rec.classFile.length < 5 || !zray.getFileActions || !zray.showInIde) {
                        return val;
                    }

                    var showInIDEParams = {
                        filePath: rec.classFile,
                        line: rec.methodLine || 1,
                        fullUrl: document.location.href
                    };
                    return zray.getFileActions(val, val, rec.classFile, showInIDEParams);
                }
            },
            {
                label: 'Duration Inclusive (ms)',
                propertyName: 'duration',
                sortable: true,
                width: 150,
                getHtml: function (val, rec) {
                    if (val) {
                        val = val / 1000;
                        return val.toFixed(3);
                    }
                }
            },
            {
                label: 'Plugin::Method',
                propertyName: 'plugin',
                sortable: true,
                getHtml: function (val, rec) {
                    if (rec.pluginMethod) {
                        val = val + '::' + rec.pluginMethod;
                    }
                    if (!val || !rec.pluginFile || rec.pluginFile.length < 5 || !zray.getFileActions || !zray.showInIde) {
                        return val;
                    }

                    var showInIDEParams = {
                        filePath: rec.pluginFile,
                        line: rec.methodLine || 1,
                        fullUrl: document.location.href
                    };
                    return zray.getFileActions(val, val, rec.pluginFile, showInIDEParams);
                }
            },
            {
                label: 'Count',
                propertyName: 'count',
                sortable: true,
                width: 90
            }
        ]);
        // create main table - end

        // create pager
        zray.createPager(storage, jQuery('#magento-intercepted-pager'));
        // create search
        zray.createSearch(storage, jQuery('#magento-intercepted-search'), maintable);

        zray.registerDataHandler('Magento2', 'intercepted', function (extensionData, requestData) {

            storage.setData(extensionData);
            zray.updateMenuTitle('Magento2', 'intercepted', 'Intercepted methods (' + extensionData.length + ')');
        });

    })();
</script>
