<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
$tableParams = [
    'tableId' => 'mage2-objects-tree',
    'tableWidth' => '4',
];
?>

<div>
    <?php echo $this->zrayTable($tableParams); //zrayTableHtml ?>
</div>

<script type="text/javascript">

    (function () {
        var storage = zray.getStorage('objects');
        // create main table
        var maintable = zray.createGeneralTreeTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
        maintable.setColumns([
            {
                label: 'Class',
                propertyName: 'class',
                sortable: true,
                getHtml: function (val, rec) {
                    if (!val || !rec.classFile || rec.classFile.length < 5 || !zray.getFileActions || !zray.showInIde) {
                        return val;
                    }
                    var showInIDEParams = {filePath: rec.classFile, line: 1, fullUrl: document.location.href};
                    return zray.getFileActions(val, val, rec.classFile, showInIDEParams);
                }
            },
            {
                label: 'Duration (ms)',
                propertyName: 'duration',
                sortable: true,
                width: 100
            }
        ]);
        // create main table - end
        // create pager
        zray.createPager(storage, jQuery('#magento-objects-pager'));
        // create search
        zray.createSearch(storage, jQuery('#magento-objects-search'), maintable);

        zray.registerDataHandler('Magento2', 'objects', function (extensionData, requestData) {
            storage.setData(extensionData);
            zray.updateMenuTitle('Magento2', 'objects', 'Created objects (' + extensionData.length + ')');
        });

    })();
</script>
