<?php
$tableParams = [
    'tableId' => 'mage2-plugins-tree',
    'tableWidth' => '4',
];
?>

<div>
    <?php echo $this->zrayTable($tableParams); //zrayTableHtml ?>
</div>

<script type="text/javascript">

    (function () {
        var storage = zray.getStorage('plugins');
        // create main table
        var maintable = zray.createGeneralTreeTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
        maintable.setColumns([
            {
                label: 'Code',
                propertyName: 'code',
                sortable: true
            },
            {
                label: 'Type',
                propertyName: 'type',
                sortable: true,
                getHtml: function (val, rec) {
                    if (!val || !rec.typeFile || rec.typeFile.length < 5 || !zray.getFileActions || !zray.showInIde) {
                        return val;
                    }
                    var showInIDEParams = {filePath: rec.typeFile, line: 1, fullUrl: document.location.href};
                    return zray.getFileActions(val, val, rec.typeFile, showInIDEParams);
                }
            },
            {
                label: 'Plugin instance',
                propertyName: 'instance',
                sortable: true,
                getHtml: function (val, rec) {
                    if (!val || !rec.instanceFile || rec.instanceFile.length < 5 || !zray.getFileActions || !zray.showInIde) {
                        return val;
                    }
                    var showInIDEParams = {filePath: rec.instanceFile, line: 1, fullUrl: document.location.href};
                    return zray.getFileActions(val, val, rec.instanceFile, showInIDEParams);
                }
            }
        ]);
        // create main table - end
        // create pager
        zray.createPager(storage, jQuery('#magento-plugins-pager'));
        // create search
        zray.createSearch(storage, jQuery('#magento-plugins-search'), maintable);

        zray.registerDataHandler('Magento2', 'plugins', function (extensionData, requestData) {
            storage.setData(extensionData);
            zray.updateMenuTitle('Magento2', 'plugins', 'Plugins (' + extensionData.length + ')');
        });

    })();
</script>
