<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
$tableParams = [
    'tableId' => 'mage2-rendered-blocks-tree',
    'tableWidth' => '4',
];
?>

<div>
    <?php echo $this->zrayTable($tableParams); //zrayTableHtml ?>
</div>

<script type="text/javascript">

    (function () {
        var storage = zray.getStorage('renderedBlocks');
        // create main table
        var maintable = zray.createGeneralTreeTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
        maintable.setColumns([
            {
                label: 'Class',
                propertyName: 'class',
                sortable: true,
                getHtml: function (val, rec) {
                    if (!val || !rec.classFile || rec.classFile.length < 5 || !zray.getFileActions || !zray.showInIde) {
                        return val;
                    }
                    var showInIDEParams = {filePath: rec.classFile, line: 1, fullUrl: document.location.href};
                    return zray.getFileActions(val, val, rec.classFile, showInIDEParams);
                }
            },
            {
                label: 'Section',
                propertyName: 'name_in_layout',
                sortable: true
            },
            {
                label: 'Duration (ms)',
                propertyName: 'render_time',
                sortable: true,
                width: 100
            },
            {
                label: 'Template',
                propertyName: 'template',
                sortable: true,
                getHtml: function (val, rec) {
                    if (!val || !rec.templateFile || rec.templateFile.length < 5 || !zray.getFileActions || !zray.showInIde) {
                        return val;
                    }
                    var showInIDEParams = {filePath: rec.templateFile, line: 1, fullUrl: document.location.href};
                    return zray.getFileActions(val, val, rec.templateFile, showInIDEParams);
                }
            },
            {
                label: 'View Variables',
                propertyName: 'view_variables',
                sortable: true
            },
            {
                label: 'Cached',
                propertyName: 'in_cache',
                sortable: true,
                getHtml: function (val, rec) {
                    if (val) {
                        return 'Yes';
                    } else {
                        return 'No';
                    }
                },
                width: 70
            }
        ]);
        // create main table - end
        // create pager
        zray.createPager(storage, jQuery('#magento-rblocks-pager'));
        // create search
        zray.createSearch(storage, jQuery('#magento-rblocks-search'), maintable);

        zray.registerDataHandler('Magento2', 'renderedBlocks', function (extensionData, requestData) {
            storage.setData(extensionData);
            zray.updateMenuTitle('Magento2', 'renderedBlocks', 'Rendered Blocks (' + extensionData.length + ')');
        });

    })();
</script>
